### ISSUE TITLE
First-Class Classes

### ISSUE THREAD

**Issue by potanin** [wyvernlang/wyvern#10]

**Comment by RobbieMcKinstry** [comment]
@potanin Can you clarify this a bit? I'm not sure what you mean. :)

**Comment by potanin** [comment]
Umm. This one is old. If we have first class classes (i.e. you can instantiate an object which is a class and add methods and fields to it during run time) then its done? ;-)

**Comment by qweasd1** [comment]
@RobbieMcKinstry Hi, I guess this [paper](http://www.cs.cmu.edu/~aldrich/papers/ecoop15-tags.pdf) might be helpful for you  :-)

From my point view, I think the concept is quite like why we say function is the first-citizen in functional language. In function language, we treat function as a kind of object. We can use lambda expression to define them in our statement and store them in variable, pass them as parameter into method. I guess here, when we say "first-class" class, we actually mean, we can construct a class definition in our statement and like what we did in functional programming, we can store them and we can pass them as parameter into method. 

For the benefits, one I think is we can compose class definition on the fly in our code, which let us writing meta program more easily. Think how flexible when we can use the high order function in functional programming, and then think we can now not only let function generate on the fly but also let class definition generate on the fly. The program might be more flexible.

It's my own opinion, hope this will be helpful to you.

**Comment by RobbieMcKinstry** [comment]
:+1:

**Comment by JonathanAldrich** [comment]
Should happen naturally when we re-implement classes within modules.  Closing for now.
