### ISSUE TITLE
Setter methods generate type error

### ISSUE THREAD

**Issue by mplamann** [wyvernlang/wyvern#138]
As of commit 12d80, the following Wyvern code no longer typechecks:

```
val obj = new
  var x : Int = 0
  def setX(x : Int) : Unit
    0
obj.setX(2)
```

It fails with the error
`this is not a subtype of this on line number error.wyv:1,11`

This code compiled on previous commits. It seems to be related to the name "setX", as the code

```
val obj = new
  var x : Int = 0
  def setY(x : Int) : Unit
    0
obj.setY(2)
```

compiles without error

**Comment by craigthelinguist** [comment]
I think this has to do with how getters/setters are auto-generated for var fields. The above P.R. has more info

**Comment by JonathanAldrich** [comment]
fixed
