### ISSUE TITLE
check that filenames and type or module names match, including capitalization

### ISSUE THREAD

**Issue by potanin** [wyvernlang/wyvern#188]
Somebody needs to investigate and tidy up - also other naming conventions we use.

**Comment by potanin** [comment]
There is more to this issue by the way. It appears that capitalisation of type declaration and file name is not checked and does not match. So type io in file IO works by declaring it as IO when using/referring to it. And if the file is mistakenly named io.wyt then on Windows and Mac it can still be used as IO but on Linux it requires matching capitalisation and needs io! TBC.

**Comment by JonathanAldrich** [comment]
io is a module (i.e. a .wyv file), not a type (i.e. a .wyt file), so lowercase is correct.

**Comment by JonathanAldrich** [comment]
I changed the title of the issue to reflect that the problem we need to fix (unless I'm mistaken in my comment above) is making sure that Wyvern checks that the name of a module or a type matches the name of the file, including capitalization

**Comment by JonathanAldrich** [comment]
Related: anything that is a type (i.e. declared in .wyt, but also types declared elsewhere) should be capitalized, and things that are values should not be capitalized (except, possibly, for the objects associated with classes, if we ever have those -- see Scala's design).

**Comment by JonathanAldrich** [comment]
Also related: for module names, it might be natural to choose a convention that there is no camelcase--just lower case, and avoiding multiple words but using dot separation where needed.  This would be similar to Java or Go.

Go also has a nice solution for exporting names from a package without requiring those names to exactly match the name of a compilation unit.  Although I like the Java solution, we might consider this given that Wyvern views modules as objects and we might consider supporting module == all files in a directory in addition to module == one file.  One reference: https://medium.com/rungo/everything-you-need-to-know-about-packages-in-go-b8bac62b74cc
