### ISSUE TITLE
Add else if

### ISSUE THREAD

**Issue by hcnelson99** [wyvernlang/wyvern#223]

**Comment by JonathanAldrich** [comment]
I'm tempted to fix this one with an "elif" construct similar to Python's.

The fix would go in stdlib/wyvern/IfTSL.wyv.  The idea is to try to match both "else" and "elif".  If "elif" parsing succeeds, then we parse the condition and then call the IfTSL parser recursively to do the rest of the nested if statement.  The recursive call may require a bit of restructuring in IfTSL.wyv.

Actually, one way to parse the "elif" would be to rewrite everything from the elif onward, replacing elif with "if" and indenting the rest of the code by one space or something.  Then we could parse that as an expression; the recursive parsing call would view the "elif" as an "if".

**Comment by hcnelson99** [comment]
Closed by 32bd81d6fdafe25f6cceb343ad335587ab2297b7
