### ISSUE TITLE
Comments are not working

### ISSUE THREAD

**Issue by TroyShaw** [wyvernlang/wyvern#23]
Both single-line and multi-line comments are not working:

//this is an error

/* This
 is an
 error */

Both result in errors while parsing.

**Comment by ewang12** [comment]
Has anyone been working on this? If not, I can take it on.

**Comment by ewang12** [comment]
Correct me if I'm wrong, but this seems to no longer be an issue.

**Comment by RobbieMcKinstry** [comment]
Looks like we have tests [here](https://github.com/wyvernlang/wyvern/blob/master/tools/src/wyvern/tools/tests/CopperTests.java#L300), which fail when uncommented, so I don't think comments work yet @ewang12 .

**Comment by JonathanAldrich** [comment]
Fixed in the new parser (still broken in the old, but won't fix there)
