### ISSUE TITLE
Match branches cannot return different data constructors

### ISSUE THREAD

**Issue by justinlubin** [wyvernlang/wyvern#236]
A match expression that returns different data constructors for the same type constructor does not typecheck. For example,
```
datatype T
  A(x : Int)
  B(x : Int)

def foo(t : T) : T = match t:
  a:A => A(0)
  b:B => B(0)
```
results in the following compiler error:
```
Type of this case branch does not match the first case branch:
```
A workaround for this is to define an identity function with the correct type, so that the return type of each branch is precisely the same:
```
datatype T
  A(x : Int)
  B(x : Int)

def id(t : T) : T
  t

def foo(t : T) : T = match t:
  a:A => id(A(0))
  b:B => id(B(0))
```
The workaround works as expected.

The main issue at hand here is that the typechecker would need to determine the common superclass of all the branches. This could run into some tricky situations, however (there may not be a unique "most specific" superclass). I believe that @hcnelson99 is more familiar with this kind of scenario and can explain how this is related to #213.

**Comment by JonathanAldrich** [comment]
Main fix: use expected type
 - verify that this works inside, for nested matches

Secondary fix: have error message when matches don't match each other suggest an annotation so that there is an expected type for the match.

**Comment by hcnelson99** [comment]
Am I off course that solving this in full generality involves union types (as does properly typing if as in #213)?

Imagine we had types with the following subtyping relationship:
```
             A
            / \
           /   \
          B     C
          | \ / |
          | / \ |
          D     E
```

If we had a `val x = match ...` where the arms of the match had values of type D and E, we need union types to express the type of x (unless we arbitrarily select B, C, or A as its type).

**Comment by JonathanAldrich** [comment]
Yes, that's right--full generality requires union types.

**Comment by JonathanAldrich** [comment]
This works now when an expected type is given (as it is in the example code given).  So I'm going to close this.
