### ISSUE TITLE
Effects declared in a pure module can’t be used inside it

### ISSUE THREAD

**Issue by Darya-** [wyvernlang/wyvern#286]
In a pure module, effects declared in the same module can be used neither in method annotations (see the `testNetwork18` test in [the effect-system tests](https://github.com/wyvernlang/wyvern/blob/master/tools/src/wyvern/tools/tests/EffectSystemTests.java)) nor in a definition of another effect (see the `testNetwork19` test in [the effect-system tests](https://github.com/wyvernlang/wyvern/blob/master/tools/src/wyvern/tools/tests/EffectSystemTests.java)).

_Expected behavior:_ Type checks with no problems

_Actual behavior:_ Error: Effect not found

**Comment by JonathanAldrich** [comment]
Fixed the testNetwork18 bug in my push today.  Still need to work on testNetwork19.
