### ISSUE TITLE
Implement field writes in the new IL

### ISSUE THREAD

**Issue by JonathanAldrich** [wyvernlang/wyvern#34]
Get ILTests.testVarFieldWrite() working.  This will involve:
 * implement wyvern.target.corewyvernIL.expressions.Assignment.generateIL() to create a FieldSet
 * implement wyvern.target.corewyvernIL.expression.FieldSet (toString, typecheck, interpret)

**Comment by craigthelinguist** [comment]
I'm having a go at this one.

(P.s. happy holidays everyone!)

**Comment by RobbieMcKinstry** [comment]
Thanks Craig! :)
