### ISSUE TITLE
Get type declarations working in the new IL

### ISSUE THREAD

**Issue by JonathanAldrich** [wyvernlang/wyvern#35]
Get ILTests.testType() and ILTests.testTypeAbbrev() working.  This will involve enhancing IL generation to generate a TypeDeclaration in the appropriate place, and then implementing typecheck() and interpret() properly.

**Comment by JonathanAldrich** [comment]
This feature should probably be implemented after Yangqingwei's module system pull request goes through, as that pull request may include some IL generation already

**Comment by JonathanAldrich** [comment]
Update: Yangqingwei's pull request went through, and I just tweaked it to get ILTests.testType() to work.  This task remains open because we would like testTypeAbbrev() to work too!

**Comment by qweasd1** [comment]
Hi Professor Jonathan, I'm Wang Zhendong I want to take this task!

**Comment by qweasd1** [comment]
@JonathanAldrich Hi Professor Jonathan, I'm Wang Zhendong. I've made it work and sent the sample code to your e-mail. :)

**Comment by JonathanAldrich** [comment]
Dear Wang Zhendong,

Thank you for working on this.  I didn't get your email, though.  Can you create a pull request?  Then I can look at your code, give you any necessary feedback, and integrate it when it is ready.

**Comment by qweasd1** [comment]
@JonathanAldrich 
Sure, maybe the attachment is too big and the e-mail is blocked. Let me prepare it ready tonight!

**Comment by JonathanAldrich** [comment]
Thank you for your code implementing this functionality!
