### ISSUE TITLE
Get delegation working in the IL

### ISSUE THREAD

**Issue by JonathanAldrich** [wyvernlang/wyvern#36]
Get ILTests.testSimpleDelegation() working

This depends on ILTests.testType() functionality, so do it after the type declarations enhancement

**Comment by qweasd1** [comment]
i think i can work on this after the the pull request for issue #35 is accepted :)

**Comment by craigthelinguist** [comment]
Hi qweasd1, are you still working on this issue?

**Comment by qweasd1** [comment]
@craigthelinguist Hi craigthelinguist, this issue is finished now and the code is merged in #55 pull request. Sorry for the late reply!

**Comment by craigthelinguist** [comment]
No worries. I started working on this issue and then I later saw your comment--but it's all good now :)

**Comment by qweasd1** [comment]
@craigthelinguist You are so kind. BTW, you can try the '@' function in the future, and we will receive a notification for it once you leave a comment here! My email address is qweasd1z1z@163.com, feel free to contact me if you have any questions, I will check the emails and give quick reply every day.

**Comment by craigthelinguist** [comment]
Cool! I didn't know about that feature. Thanks again, @qweasd1

**Comment by qweasd1** [comment]
@craigthelinguist  :-) np, have fun with Wyvern!

**Comment by JonathanAldrich** [comment]
This is working now, thanks for the PR!
