### ISSUE TITLE
Call simple Java functions from Wyvern

### ISSUE THREAD

**Issue by JonathanAldrich** [wyvernlang/wyvern#38]
Do the following:
 * add a package wyvern.target.corewyvernIL.interop
 * implement a class JavaObject in that package
 * have JavaObject extend wyvern.target.corewyvernIL.expression.Invokable
 * create a constructor for a JavaObject that takes a (Java) Object to wrap
 * create a test method in ILTests
      - creates a JavaObject wrapping java.lang.System.out
      - creates a MethodCall that invokes "println" on the JavaObject, passing an IntegerLiteral as argument
      - calls interpret() on the MethodCall

**Comment by bravenewprince** [comment]
Looks pretty straight forward. Assign this over to me and I'll get started! ^.^

**Comment by RobbieMcKinstry** [comment]
I'm going to take another look at this over the holiday. :-)

**Comment by JonathanAldrich** [comment]
Great!

I actually did some preliminary work on this, enough to call a simple function that takes an int and returns an int.  I think the design is pretty extensible, so hopefully the next few steps should be straightforward.  Have a look at ILTests.java, in particular testJavaImportLibrary1, testJavaImportLibrary2, and testJavaImport1.  The classes JavaImporter and JObject are part of a generic Java access library that is essentially a convenience wrapper to Java reflection.  The class JavaValue actually represents a Java object inside a Wyvern program that is being interpreted.  The code that interprets Java imports is in ModuleDeclaration.java.

**Comment by JonathanAldrich** [comment]
Some good next steps might be to support calling methods that take Strings as arguments, and to support importing a class (not just a static field of a class).

**Comment by JonathanAldrich** [comment]
Update: I added 3 tests in ILTests.java to guide this:

 * First, implement StringLiteral in a way that echos IntegerLiteral.  Include hashCode(), equals(), toString(), and typeCheck().

 * Then make sure that testIdentityCallString() and testLetValWithString() work in ILTests

 * Extend javaToWyvern and wyvernToJava in JavaValue and also GenUtil.javaClassToWyvernTypeRec to handle strings as well as integers

 * Then make sure that ILTests.testJavaImport2() works

**Comment by RobbieMcKinstry** [comment]
Completed by https://github.com/wyvernlang/wyvern/pull/51

I'll open another issue for the next story in Java interop.
