### ISSUE TITLE
Add lambda syntax and codegen to Wyvern

### ISSUE THREAD

**Issue by JonathanAldrich** [wyvernlang/wyvern#40]
Get ILTests.testLambda() working.  This should involve:
* adding appropriate productions to the parser, that generate a lambda in the TypedAST
* translating the lambda expression into an equivalent "new" statement in the Wyvern IL that creates an object with an apply() method taking the same arguments that the lambda took

**Comment by RobbieMcKinstry** [comment]
I've started on this; I have the parsing going (small bug which might require eyes in code review). I'm going to push to a branch around EOD tomorrow. Tomorrow I'm going to work on getting the typechecking going. I might reach out for direction but I want to plug in another 3 hours before I ask for help.

**Comment by RobbieMcKinstry** [comment]
Still working on this. I'm working on generating the IL from the TypedAST.

**Comment by RobbieMcKinstry** [comment]
https://github.com/wyvernlang/wyvern/pull/46

I feel like I've lived a thousand life-times since I started this issue. (It's been over a month!) Glad to have it winding down XD

**Comment by JonathanAldrich** [comment]
Completed with this last PR.  Thanks Robbie!
