### ISSUE TITLE
Interpreter gives parse error on hello world

### ISSUE THREAD

**Issue by craigthelinguist** [wyvernlang/wyvern#44]
I set up the interpreter by running ant build. To use the interpreter I run wyvern.tools.interpreter as main, passing in as argument the file to interpret. Here's an example program which I'm able to get working:

<pre><code>def fib (x : Int) : Int
	if (x == 1) || (x == 2) then
		1
	else
		fib(x-1) + fib(x-2)
		
fib(3)
</code></pre>

However, the hello world program described in https://github.com/wyvernlang/docs/blob/master/guide/wyvern-guide.pdf gives the following parsing error:

<pre><code>Parsing error: Error at line 2, column 8 in file examples/hello.wyv
         (parser state: 6; real character index: 8):
  Expected a token of one of the following types:
   [$,Dedent_t,Newline_t,Spaces_t,and_t,
    bar_t,closeParen_t,colon_t,comma_t,comment_t,
    dash_t,divide_t,dot_t,dslSignal_t,elseKwd_t,
    equals_t,equalsequals_t,gt_t,ignoredNewline,lt_t,
    mult_t,multi_comment_t,newSignal_t,openParen_t,plus_t,
    thenKwd_t]
   Input currently matches:
   [notCurly_t]
	at wyvern.tools.parsing.Wyvern.reportSyntaxError(Wyvern.java:57)
	at edu.umn.cs.melt.copper.runtime.engines.single.SingleDFAEngine.runEngine(SingleDFAEngine.java:475)
	at wyvern.tools.parsing.Wyvern.parse(Wyvern.java:4088)
	at wyvern.tools.Interpreter.main(Interpreter.java:36)
</code></pre>

Any ideas what I am doing wrong?

**Comment by JonathanAldrich** [comment]
We are evolving from an older implementation to a newer one.  Right now wyvern.tools.Interpreter uses the old infrastructure, but the requires keyword (and other aspects of modules) are only in the newer implementation.

To fix this, we need to create an Interpreter class that uses the new implementation.  See ILTest for some working test cases that use this newer implementation.  We will also need to actually implement the required stdout library, too, which means fixing Java interop with Strings.

Sadly if we fix this, your fib() example will stop working, but we're not far from getting it to work again in the new system!

**Comment by craigthelinguist** [comment]
Cheers Jonathan!

**Comment by RobbieMcKinstry** [comment]
Is this a reasonable issue for me to look at? (I realize it's closed, but I'd like a working interpreter to try out code I put on the Wyvern website.)

**Comment by JonathanAldrich** [comment]
Actually yes, it would be good to rename wyvern.tools.Interpreter to wyvern.tools.OldInterpreter or something (keeping it in the repo for now so we can still run the old code if needed) and writing a new wyvern.tools.Interpreter that reads the command like as the current Interpreter does but then sets things up for execution like the code in ILTests.

**Comment by RobbieMcKinstry** [comment]
I'm on it boss! 
I think this will be more beneficial than the error messages story since it'll free me up to write short guides on the language on the website. For me, writing a guide is my way of learning the language.

**Comment by RobbieMcKinstry** [comment]
Closed by #56
